baseURL = "https://reveristdarkmoth.github.io"
languageCode = "en-US"
title = "Reverist Dark Moth's blog"

canonifyurls = true
# Number of posts per page on the home page

[pagination]
pagerSize = 100


# Load the theme
[module]
  [[module.imports]]
    path = 'github.com/brihadeesh/hugo-tufte'

# Only modify the following if you know what you are doing
[markup]
  [goldmark]
    [renderer]
      unsafe = true
  [highlight]
    noClasses = false
    guessSyntax = true

[params]
  # Subtitle of the website
  subtitle = "Subtitle for your site"
  favicon = "/favicon.ico"
  touchicon = "/apple-touch-icon.png"

  homeCollection = "posts"

  # Customize the indicator for margin notes
  # Some suggestions = âŠ•, ğŸ’¬, ğŸ’­, ğŸ“‘, ğŸ·, âœ, ğŸ’¡, ğŸ§, ğŸ“, ğŸ“Œ
  marginNoteInd = "âŠ•"
  # Your name or the name of you
  copyright = "Copyright &copy; 2025 Reverist Dark Moth."
  # Show the "Powered by Hugo-Tufte and Hugo."
  showPoweredBy = false
  # Make the page centred in screen
  centerArticle = false


# [taxonomies]
#   category = categories
#   series = series
#   tag = tags
